# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
name: Nemesis
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        container:
              image: golang:alpine
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: apk update && apk add make zip
            - name: Run tests
              run: make test
            - name: Create Coverage Artifact
              run: go tool cover -html=lambda/cover/cover.out -o coverage.html
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                name: Coverage
                path: coverage.html
    build:
        needs: test
        runs-on: ubuntu-latest
        container:
            image: golang:alpine
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: apk update && apk add make
            - name: Build
              run: make build
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                name: kinesis_scaling.zip
                path: lambda/kinesis_scaling.zip