name: Nemesis
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        container:
              image: golang:alpine
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              runs: apk update && apk add make
